# Generated by Django 4.1.2 on 2022-10-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0006_remove_favorite_updated_at_alter_favorite_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, default='Anonymous', max_length=200, null=True),
        ),
    ]
